#!/bin/sh
# This check checks the overall state of a host group. 
# It fetches the current state of all hosts of a group
# via livestatus (the path to the livestatus socket is
# provided as a third, optional parameter).
# 
# Provide the name of the host group as first
# parameter.
#
# If you specify a number NUM as second parameter,
# then the state of this check is not considered to
# be the worst host state of the group but the
# NUM'th worst state. E.g. if there is one up
# and one unreachable host, then specifying 2 will
# result in a unreachable state and 3 in a Up state.
#
# WARN is considered to be worse than UNKNOWN.

GROUPNAME=$1
if [ -z "$GROUPNAME" ] ; then
    echo "Usage: $0 HOST_GROUP [NUM [SOCKET] ]"
    exit 3
fi
NUM=${2:-1}
SOCKET=${3:-$OMD_ROOT/tmp/run/live}

check ()
{
  IFS=\; read COUNT UP DOWN UNREACH
  if [ $DOWN -ge $NUM ]
  then
      status=DOWN
      exitcode=2
  elif [ $((UP + UNREACH)) -ge $NUM ] ; then
      status=UNREACH
      exitcode=1
  else
      status=OK
      exitcode=0
  fi
  echo "$status - $COUNT hosts: $DOWN Down, $UNREACH Unreachable, $UP Up"
  exit $exitcode
}

cat <<EOF | unixcat $SOCKET | check
GET hosts
Filter: groups >= $GROUPNAME
Stats: last_hard_state >= 0
Stats: last_hard_state = 0
Stats: last_hard_state = 1
Stats: last_hard_state = 2
EOF
